---
title: '20200407'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

```{r}
# 用vector儲存
c("2020-03-31T13:40:55Z" ,
  "一芳" ,
  "2" ,
  "水果茶")
  
  #用list儲存
  library(lubridate)
`小明交易1` <- list(
    ymd_hms("2020-03-31T13:40:55Z"),
    "一芳",
    2 ,
    "水果茶"
  )
print(`小明交易1`)
```
```{r}
c(
  c("108-1","高級會計學","高等統計學"), 
  c("108-2","食在拉丁美洲") 
)
```
```{r}
list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
```
```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```
```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```
```{r}
commit <- list(
  author = list(
    name="Martin老師", 
    email="mtlin@gm.ntpu.edu.tw", 
    time=ymd_hms("2020-03-25T07:17:40Z")
  ),
  commiter = list(
    name="emilyluckey", 
    email="emily007@gmail.com", 
    time=ymd_hms("2020-03-26T08:18:40Z")
  ),
  message = "update"
)
print(commit)
```

















